### PR TITLE
Split vintage block texture into background and foreground.

### PR DESCRIPTION
**Pull request by doxygen-spammer**
Extracted from #5. This will facilitate creation of dim variants of the vintage light blocks.

### CODE REVIEW

**Comment by random-geek** [comment]
Does this help with the morelights_dim mod, or is it just to make future changes easier?

**Comment by doxygen-spammer** [comment]
Yes, this is for morelights_dim. There isn’t really another purpose.

**Comment by random-geek** [comment]
Is there a reason not to include these textures in morelights_dim and use `override_item` to redefine the textures?

**Comment by doxygen-spammer** [comment]
I think that would be less elegant. But that is already the only reason. :D

**Comment by random-geek** [comment]
Would it be okay if I used the light portion of the light block as the background, and the darker frame part as the overlay? It might be a more elegant solution since there isn't currently another use for the frame material.

**Comment by doxygen-spammer** [comment]
That should be okay. For morelights_dim at least it would be perfectly okay, 
since it only needs the light part to be separate in any way..

**Comment by random-geek** [comment]
Just released the changes, they should be on ContentDB now.

**Pull request merged**
